// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devPartnerTest.Data;

namespace devPartnerTest.Migrations
{
    [DbContext(typeof(devPartnerContext))]
    [Migration("20210802000703_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("devPartnerTest.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cnpjDestinatarioNf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cnpjEmissorNf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataNf")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroNf")
                        .HasColumnType("int");

                    b.Property<double>("valorTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("NotaFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
